let runtimeKey = null;
let runtimeModel = null;
let runtimeEndpoint = null;
let runtimeProvider = null;
let runtimeProtocol = null;
function keyOf(env) { return runtimeKey === null ? (env.FH_AI_KEY || '') : runtimeKey; }
function modelOf(env) { return runtimeModel === null ? (env.FH_AI_MODEL || '') : runtimeModel; }
function endpointOf(env) { return runtimeEndpoint === null ? (env.FH_AI_ENDPOINT || '') : runtimeEndpoint; }
function providerOf(env) { return runtimeProvider === null ? (env.FH_AI_PROVIDER || 'openrouter') : runtimeProvider; }
function protocolOf(env) { return runtimeProtocol === null ? (env.FH_AI_PROTOCOL || 'openai-compatible') : runtimeProtocol; }
function json(body, status = 200) { return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type,Authorization' } }); }
function admin(req, env) { return !!env.FH_ADMIN_TOKEN && req.headers.get('Authorization') === `Bearer ${env.FH_ADMIN_TOKEN}`; }
function superAdmin(req, env) { return !!env.FH_SUPER_ADMIN_TOKEN && req.headers.get('Authorization') === `Bearer ${env.FH_SUPER_ADMIN_TOKEN}`; }
async function proxy(env, messages, maxTokens, temperature = 0.7) {
  const endpoint = endpointOf(env), key = keyOf(env), model = modelOf(env), protocol = protocolOf(env);
  if (!endpoint || !key || !model) return json({ ok: false, code: 'AI_NOT_CONFIGURED', msg: 'Sites 尚未配置学校 AI 服务' }, 503);
  try { const anthropic = protocol === 'anthropic-messages'; const headers = anthropic ? { 'Content-Type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' } : { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }; const body = anthropic ? { model, system: messages.filter(m => m.role === 'system').map(m => m.content).join('\n'), messages: messages.filter(m => m.role !== 'system'), max_tokens: maxTokens, temperature } : { model, messages, max_tokens: maxTokens, temperature }; const r = await fetch(endpoint, { method: 'POST', headers, body: JSON.stringify(body) }); const data = await r.json().catch(() => ({})); if (!r.ok) return json({ ok: false, code: r.status === 401 ? 'AUTH_EXPIRED' : r.status === 429 ? 'RATE_LIMITED' : 'UPSTREAM_ERROR', msg: data.error?.message || `模型服务返回 HTTP ${r.status}` }, r.status); return json({ ok: true, content: anthropic ? (data.content?.[0]?.text || '') : (data.choices?.[0]?.message?.content || ''), model }); } catch { return json({ ok: false, code: 'NETWORK_ERROR', msg: '无法连接在线 AI 服务' }, 502); }
}
export default { async fetch(request, env) {
  const url = new URL(request.url);
  if (request.method === 'OPTIONS') return new Response('', { status: 204, headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type,Authorization' } });
  if (url.pathname === '/api/ping' || url.pathname === '/api/health') return json({ ok: true, name: '凤凰花·智学站点', version: 4, apiVersion: 1, storage: 'browser-local', tokenRequired: false, collections: 16 });
  if (url.pathname === '/api/ai/status') { const key = keyOf(env), model = modelOf(env); return json({ ok: true, configured: !!(endpointOf(env) && model && key), credential: key ? 'server' : 'missing' }); }
  if (url.pathname === '/api/super-admin/ai-config' || url.pathname === '/api/admin/ai-key') return json({ ok: false, code: 'ONLINE_AI_CONFIGURATION_REMOVED', msg: '在线 AI 密钥配置入口已移除；请只在服务端环境变量中配置 AI 服务' }, 404);
  if (url.pathname === '/api/super-admin/ai-config') { if (!superAdmin(request, env)) return json({ ok: false, msg: '超级管理员服务端授权失败' }, 401); if (request.method === 'GET') return json({ ok: true, configured: !!(endpointOf(env) && modelOf(env) && keyOf(env)), provider: providerOf(env), protocol: protocolOf(env), endpoint: endpointOf(env), model: modelOf(env), masked: keyOf(env) ? `••••${keyOf(env).slice(-4)}` : '' }); if (request.method === 'PUT') { const b = await request.json().catch(() => ({})); const provider = String(b.provider || providerOf(env)); const protocol = String(b.protocol || protocolOf(env)); const endpoint = String(b.endpoint || endpointOf(env)).trim(); const model = String(b.model || modelOf(env)).trim(); if (!['openrouter','openai-compatible','anthropic'].includes(provider) || !['openai-compatible','anthropic-messages'].includes(protocol) || !/^https:\/\/.{4,512}$/.test(endpoint) || !/^[A-Za-z0-9._:/-]{2,160}$/.test(model)) return json({ok:false,msg:'服务商、协议、endpoint 或模型名称不正确'},400); if (b.key !== undefined && (String(b.key).trim().length < 8 || String(b.key).trim().length > 512)) return json({ok:false,msg:'密钥格式不正确'},400); runtimeProvider=provider; runtimeProtocol=protocol; runtimeEndpoint=endpoint; runtimeModel=model; if (b.key !== undefined) runtimeKey=String(b.key).trim(); return json({ok:true,configured:!!keyOf(env),provider,protocol,endpoint,model,masked:keyOf(env)?`••••${keyOf(env).slice(-4)}`:'',msg:'学校 AI 接入已更新；重启后恢复环境变量'}); } if (request.method === 'POST') return proxy(env,[{role:'user',content:'只回复：正常'}],8,0); if (request.method === 'DELETE') { runtimeKey=''; runtimeModel=''; runtimeEndpoint=''; return json({ok:true,configured:false,msg:'运行时 AI 接入已清除，已回退本地审核题库'}); } return json({ok:false,msg:'method not allowed'},405); }
  if (url.pathname === '/api/admin/ai-key') { if (!admin(request, env)) return json({ ok: false, msg: '管理员服务端授权失败' }, 401); if (request.method === 'GET') return json({ ok: true, configured: !!(endpointOf(env) && modelOf(env) && keyOf(env)), credential: keyOf(env) ? 'server' : 'missing' }); if (request.method === 'POST') return proxy(env, [{ role: 'user', content: '只回复：正常' }], 8, 0); return json({ ok: false, code: 'SUPER_ADMIN_REQUIRED', msg: '仅超级管理员可修改学校 AI 接入' }, 403); }
  if (url.pathname === '/api/ai/chat' && request.method === 'POST') { const body = await request.json().catch(() => ({})); return proxy(env, body.messages || [], body.maxTokens || 1400, body.temperature); }
  if (env.ASSETS) { const path = url.pathname === '/' ? '/index.html' : url.pathname; const direct = await env.ASSETS.fetch(new Request(new URL(path, request.url), request)); if (direct.status !== 404) return direct; const client = await env.ASSETS.fetch(new Request(new URL(`/client${path}`, request.url), request)); if (client.status !== 404) return client; }
  return new Response('Not Found', { status: 404 });
} };
